let SERVELLES_ADMIN_MODE = false;
let ADMIN_HOTELS = [];
let ADMIN_MEMBERSHIPS = [];
let ADMIN_PROFILES = [];
let ADMIN_DEPARTMENTS = [];
let ADMIN_ROOMS = [];
let ADMIN_CURRENT_HOTEL = null;

function ensureAdminSidebar(){
  const shell=document.getElementById('adminShell');
  if(!shell || document.getElementById('servellesAdminNav')) return;
  const style=document.createElement('style');
  style.id='servellesAdminNavStyle';
  style.textContent=`
    .admin-topbar:after{display:none!important;content:none!important}
    .admin-brand{background:url('servelles-logo.png?v=078') center 20px/205px auto no-repeat!important;min-height:165px!important;padding-top:145px!important}
    .admin-brand-mark,.admin-brand>div{display:none!important}
    #servellesAdminNav{position:fixed;left:17px;top:165px;width:220px;z-index:5;display:grid;gap:5px;border-top:1px solid rgba(255,255,255,.09);padding-top:16px}
    #servellesAdminNav button{border:0;background:transparent;color:#d8dde2;text-align:left;padding:12px 14px;border-radius:9px;font-size:14px;cursor:pointer;display:flex;align-items:center;gap:11px}
    #servellesAdminNav button:hover,#servellesAdminNav button.active{background:linear-gradient(90deg,rgba(201,147,61,.18),rgba(255,255,255,.035));color:#fff}
    #servellesAdminNav .nav-ico{width:18px;text-align:center;color:#d8a23e}
    #servellesAdminNav .admin-add-hotel{margin-top:12px;border:1px solid rgba(216,162,62,.55);background:rgba(216,162,62,.08);color:#e2b45d}
    @media(max-width:900px){#servellesAdminNav{display:none!important}}
  `;
  document.head.appendChild(style);
  const nav=document.createElement('nav');
  nav.id='servellesAdminNav';
  nav.innerHTML=`
    <button data-admin-page="dashboard"><span class="nav-ico">⌂</span>Dashboard</button>
    <button data-admin-page="hotels" class="active"><span class="nav-ico">▣</span>Hotels</button>
    <button data-admin-page="users"><span class="nav-ico">♙</span>Users</button>
    <button data-admin-page="activity"><span class="nav-ico">◷</span>Activity Log</button>
    <button data-admin-page="integrations"><span class="nav-ico">◇</span>Integrations</button>
    <button data-admin-page="reports"><span class="nav-ico">▥</span>Reports</button>
    <button data-admin-page="billing"><span class="nav-ico">▤</span>Billing</button>
    <button data-admin-page="settings"><span class="nav-ico">⚙</span>System Settings</button>
    <button class="admin-add-hotel" data-admin-page="addhotel"><span class="nav-ico">＋</span>Add Hotel</button>`;
  shell.appendChild(nav);
  nav.addEventListener('click',e=>{
    const b=e.target.closest('button[data-admin-page]'); if(!b)return;
    nav.querySelectorAll('button').forEach(x=>x.classList.remove('active')); b.classList.add('active');
    const page=b.dataset.adminPage;
    if(page==='hotels'||page==='dashboard'){ backToHotelOverview(); loadAdminDashboard(); return; }
    if(page==='addhotel'){ alert('New hotel onboarding is the next build step.'); return; }
    showAdminPlaceholder(page,b.textContent.trim());
  });
}

function showAdminPlaceholder(page,title){
  const overview=document.getElementById('adminOverview'), manager=document.getElementById('adminManager');
  manager?.classList.add('hidden'); overview?.classList.remove('hidden');
  let panel=document.getElementById('adminPlaceholderPanel');
  if(!panel){ panel=document.createElement('section'); panel.id='adminPlaceholderPanel'; panel.className='admin-panel'; overview.appendChild(panel); }
  const summary=document.querySelector('#adminOverview .admin-summary'); const hotelsPanel=document.querySelector('#adminOverview .admin-panel:not(#adminPlaceholderPanel)');
  if(summary) summary.style.display='none'; if(hotelsPanel) hotelsPanel.style.display='none';
  panel.style.display='block';
  panel.innerHTML=`<div class="admin-panel-head"><div><span class="small-label">SERVELLE'S PLATFORM</span><h2>${adminEscape(title)}</h2></div></div><div class="admin-empty" style="margin-top:20px">${adminEscape(title)} module is ready for the next build stage.</div>`;
}
function resetAdminOverviewPanels(){
  const summary=document.querySelector('#adminOverview .admin-summary'); const panels=document.querySelectorAll('#adminOverview .admin-panel');
  if(summary) summary.style.display='grid'; panels.forEach(p=>p.style.display=p.id==='adminPlaceholderPanel'?'none':'block');
}

async function isPlatformAdmin(){ const {data,error}=await servellesDb.rpc('is_servelles_admin'); if(error) throw error; return data===true; }
function adminEscape(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function loadAdminData(){const [hotelsRes,membersRes,profilesRes,deptsRes,roomsRes]=await Promise.all([servellesDb.from('hotels').select('*').order('name'),servellesDb.from('hotel_memberships').select('*'),servellesDb.from('profiles').select('id,full_name'),servellesDb.from('departments').select('*').order('name'),servellesDb.from('rooms').select('*').order('room_number')]);for(const r of [hotelsRes,membersRes,profilesRes,deptsRes,roomsRes])if(r.error)throw r.error;ADMIN_HOTELS=hotelsRes.data||[];ADMIN_MEMBERSHIPS=membersRes.data||[];ADMIN_PROFILES=profilesRes.data||[];ADMIN_DEPARTMENTS=deptsRes.data||[];ADMIN_ROOMS=roomsRes.data||[];}
async function loadAdminDashboard(){ensureAdminSidebar();resetAdminOverviewPanels();await loadAdminData();const adminShell=document.getElementById('adminShell'),appShell=document.querySelector('.app-shell'),authScreen=document.getElementById('authScreen'),adminUser=document.getElementById('adminUser');if(adminUser)adminUser.textContent=SERVELLES_USER?.full_name||SERVELLES_USER?.email||'Servelles Admin';document.getElementById('adminHotelCount').textContent=ADMIN_HOTELS.length;document.getElementById('adminUserCount').textContent=ADMIN_MEMBERSHIPS.filter(x=>x.active).length;document.getElementById('adminDeptCount').textContent=ADMIN_DEPARTMENTS.filter(x=>x.active).length;document.getElementById('adminRoomCount').textContent=ADMIN_ROOMS.filter(x=>x.active).length;const grid=document.getElementById('adminHotelGrid');grid.innerHTML=ADMIN_HOTELS.map(h=>{const users=ADMIN_MEMBERSHIPS.filter(x=>x.hotel_id===h.id&&x.active).length,depts=ADMIN_DEPARTMENTS.filter(x=>x.hotel_id===h.id&&x.active).length,roomCount=ADMIN_ROOMS.filter(x=>x.hotel_id===h.id&&x.active).length;return `<article class="hotel-admin-card"><div class="hotel-admin-card-head"><div><span class="small-label">HOTEL ACCOUNT</span><h3>${adminEscape(h.name)}</h3></div><span class="admin-pill ${h.active?'':'off'}">${h.active?'ACTIVE':'PAUSED'}</span></div><div class="hotel-admin-meta"><div><span>Users</span><strong>${users}</strong></div><div><span>Departments</span><strong>${depts}</strong></div><div><span>Rooms</span><strong>${roomCount}</strong></div></div><div class="hotel-admin-actions"><button class="secondary-btn" onclick="enterHotelAsAdmin('${h.id}')">OPEN HOTEL</button><button class="primary-btn" onclick="adminHotelInfo('${h.id}')">MANAGE</button></div></article>`;}).join('')||'<div class="admin-empty">No hotels have been created yet.</div>';document.getElementById('adminManager')?.classList.add('hidden');document.getElementById('adminOverview')?.classList.remove('hidden');document.getElementById('returnAdminBtn')?.classList.add('hidden');authScreen?.classList.add('hidden');appShell?.classList.add('auth-locked');adminShell?.classList.remove('hidden');}
async function enterHotelAsAdmin(hotelId){const {data:hotel,error}=await servellesDb.from('hotels').select('*').eq('id',hotelId).single();if(error)return alert(error.message);SERVELLES_HOTEL=hotel;SERVELLES_MEMBERSHIP={role:'servelles_admin',hotel_id:hotel.id};const hotelName=document.querySelector('.hotel-name'),hotelSub=document.querySelector('.hotel-sub'),hotelLogo=document.querySelector('.hotel-logo'),eyebrow=document.querySelector('.topbar .eyebrow');if(hotelName)hotelName.textContent=hotel.name.toUpperCase();if(hotelSub)hotelSub.textContent='SERVELLES ADMIN ACCESS';if(hotelLogo)hotelLogo.textContent='';if(eyebrow)eyebrow.textContent=`Admin view · ${hotel.name}`;document.getElementById('returnAdminBtn')?.classList.remove('hidden');document.getElementById('adminShell')?.classList.add('hidden');document.querySelector('.app-shell')?.classList.remove('auth-locked');}
function returnToAdmin(){document.getElementById('returnAdminBtn')?.classList.add('hidden');document.querySelector('.app-shell')?.classList.add('auth-locked');loadAdminDashboard();}
async function adminHotelInfo(hotelId){await loadAdminData();ADMIN_CURRENT_HOTEL=ADMIN_HOTELS.find(h=>h.id===hotelId);if(!ADMIN_CURRENT_HOTEL)return;document.getElementById('adminOverview')?.classList.add('hidden');document.getElementById('adminManager')?.classList.remove('hidden');document.getElementById('manageHotelTitle').textContent=ADMIN_CURRENT_HOTEL.name;document.getElementById('manageHotelState').textContent=ADMIN_CURRENT_HOTEL.active?'ACTIVE':'PAUSED';document.getElementById('manageHotelState').className=`admin-pill ${ADMIN_CURRENT_HOTEL.active?'':'off'}`;fillHotelForm();await Promise.all([renderAdminTeam(),renderAdminDepartments(),renderAdminRooms(),renderAdminIntegrations()]);}
function backToHotelOverview(){ADMIN_CURRENT_HOTEL=null;document.getElementById('adminManager')?.classList.add('hidden');document.getElementById('adminOverview')?.classList.remove('hidden');resetAdminOverviewPanels();}
function fillHotelForm(){const h=ADMIN_CURRENT_HOTEL;document.getElementById('hotelNameInput').value=h.name||'';document.getElementById('hotelShortNameInput').value=h.short_name||'';document.getElementById('hotelEmailInput').value=h.contact_email||'';document.getElementById('hotelPhoneInput').value=h.phone||'';document.getElementById('hotelAddressInput').value=h.address||'';document.getElementById('hotelNotesInput').value=h.notes||'';document.getElementById('hotelActiveInput').checked=!!h.active;}
async function saveHotelDetails(){const h=ADMIN_CURRENT_HOTEL;const patch={name:document.getElementById('hotelNameInput').value.trim(),short_name:document.getElementById('hotelShortNameInput').value.trim()||null,contact_email:document.getElementById('hotelEmailInput').value.trim()||null,phone:document.getElementById('hotelPhoneInput').value.trim()||null,address:document.getElementById('hotelAddressInput').value.trim()||null,notes:document.getElementById('hotelNotesInput').value.trim()||null,active:document.getElementById('hotelActiveInput').checked};const {error}=await servellesDb.from('hotels').update(patch).eq('id',h.id);if(error)return alert(error.message);Object.assign(h,patch);document.getElementById('manageHotelTitle').textContent=h.name;toastAdmin('Hotel details saved');}
async function removeCurrentHotel(){const h=ADMIN_CURRENT_HOTEL;if(!h)return;const warning=`REMOVE ${h.name}?\n\nThis permanently removes the hotel and linked Servelles hotel data. Supabase Auth user accounts are not deleted.\n\nPress OK to continue.`;if(!confirm(warning))return;const typed=prompt(`Type the hotel name exactly to confirm deletion:\n\n${h.name}`);if(typed===null)return;if(typed.trim()!==h.name){alert('Hotel name did not match. Nothing was deleted.');return;}const finalCheck=confirm(`Final confirmation: permanently remove ${h.name}?`);if(!finalCheck)return;const {error}=await servellesDb.from('hotels').delete().eq('id',h.id);if(error){alert(`Could not remove hotel: ${error.message}\n\nIf this is a permissions error, run the latest admin-management-setup.sql in Supabase.`);return;}ADMIN_CURRENT_HOTEL=null;toastAdmin(`${h.name} removed`);await loadAdminDashboard();}
async function renderAdminTeam(){const members=ADMIN_MEMBERSHIPS.filter(m=>m.hotel_id===ADMIN_CURRENT_HOTEL.id),profiles=new Map(ADMIN_PROFILES.map(p=>[p.id,p])),box=document.getElementById('adminTeamList');box.innerHTML=members.map(m=>{const p=profiles.get(m.user_id)||{};return `<div class="manage-row"><div><strong>${adminEscape(p.full_name||'Hotel user')}</strong><span>${adminEscape(m.user_id)}</span></div><div class="manage-row-actions"><select onchange="changeMemberRole('${m.id}',this.value)">${['hotel_admin','manager','department_manager','staff'].map(r=>`<option value="${r}" ${m.role===r?'selected':''}>${r.replaceAll('_',' ')}</option>`).join('')}</select><button class="tiny-btn ${m.active?'':'muted'}" onclick="toggleMember('${m.id}',${!m.active})">${m.active?'Disable':'Enable'}</button></div></div>`;}).join('')||'<div class="admin-empty">No users assigned to this hotel.</div>';}
async function changeMemberRole(id,role){const {error}=await servellesDb.from('hotel_memberships').update({role}).eq('id',id);if(error)return alert(error.message);toastAdmin('Role updated');}async function toggleMember(id,active){const {error}=await servellesDb.from('hotel_memberships').update({active}).eq('id',id);if(error)return alert(error.message);await adminHotelInfo(ADMIN_CURRENT_HOTEL.id);}
async function renderAdminDepartments(){const items=ADMIN_DEPARTMENTS.filter(d=>d.hotel_id===ADMIN_CURRENT_HOTEL.id);document.getElementById('adminDepartmentList').innerHTML=items.map(d=>`<div class="manage-row"><div><strong>${adminEscape(d.name)}</strong><span>${d.active?'Active':'Disabled'}</span></div><button class="tiny-btn ${d.active?'':'muted'}" onclick="toggleDepartment('${d.id}',${!d.active})">${d.active?'Disable':'Enable'}</button></div>`).join('')||'<div class="admin-empty">No departments yet.</div>';}async function addDepartment(){const input=document.getElementById('newDepartmentName'),name=input.value.trim();if(!name)return;const {error}=await servellesDb.from('departments').insert({hotel_id:ADMIN_CURRENT_HOTEL.id,name});if(error)return alert(error.message);input.value='';await adminHotelInfo(ADMIN_CURRENT_HOTEL.id);}async function toggleDepartment(id,active){const {error}=await servellesDb.from('departments').update({active}).eq('id',id);if(error)return alert(error.message);await adminHotelInfo(ADMIN_CURRENT_HOTEL.id);}
async function renderAdminRooms(){const items=ADMIN_ROOMS.filter(r=>r.hotel_id===ADMIN_CURRENT_HOTEL.id);document.getElementById('adminRoomList').innerHTML=items.map(r=>`<div class="manage-row"><div><strong>Room ${adminEscape(r.room_number)}</strong><span>${adminEscape(r.room_name||'')} ${r.active?'':'· Disabled'}</span></div><button class="tiny-btn ${r.active?'':'muted'}" onclick="toggleRoom('${r.id}',${!r.active})">${r.active?'Disable':'Enable'}</button></div>`).join('')||'<div class="admin-empty">No rooms yet.</div>';}async function addRoom(){const num=document.getElementById('newRoomNumber').value.trim(),name=document.getElementById('newRoomName').value.trim();if(!num)return;const {error}=await servellesDb.from('rooms').insert({hotel_id:ADMIN_CURRENT_HOTEL.id,room_number:num,room_name:name||null});if(error)return alert(error.message);document.getElementById('newRoomNumber').value='';document.getElementById('newRoomName').value='';await adminHotelInfo(ADMIN_CURRENT_HOTEL.id);}async function toggleRoom(id,active){const {error}=await servellesDb.from('rooms').update({active}).eq('id',id);if(error)return alert(error.message);await adminHotelInfo(ADMIN_CURRENT_HOTEL.id);}
async function renderAdminIntegrations(){const [waRes,pmsRes]=await Promise.all([servellesDb.from('hotel_whatsapp_connections').select('*').eq('hotel_id',ADMIN_CURRENT_HOTEL.id).maybeSingle(),servellesDb.from('hotel_pms_connections').select('*').eq('hotel_id',ADMIN_CURRENT_HOTEL.id).maybeSingle()]);if(waRes.error)return showMigrationNeeded(waRes.error);if(pmsRes.error)return showMigrationNeeded(pmsRes.error);const wa=waRes.data||{},pms=pmsRes.data||{};document.getElementById('waDisplayNumber').value=wa.display_phone_number||'';document.getElementById('waVerifiedName').value=wa.verified_name||'';document.getElementById('waWabaId').value=wa.waba_id||'';document.getElementById('waPhoneId').value=wa.phone_number_id||'';document.getElementById('waStatus').value=wa.status||'not_connected';document.getElementById('pmsProvider').value=pms.provider||'none';document.getElementById('pmsPropertyId').value=pms.property_id||'';document.getElementById('pmsStatus').value=pms.status||'not_connected';document.getElementById('pmsNotes').value=pms.notes||'';}function showMigrationNeeded(error){console.error(error);document.getElementById('integrationMessage').textContent='Run admin-management-setup.sql in Supabase to enable integrations.';}async function saveWhatsApp(){const row={hotel_id:ADMIN_CURRENT_HOTEL.id,display_phone_number:val('waDisplayNumber'),verified_name:val('waVerifiedName'),waba_id:val('waWabaId'),phone_number_id:val('waPhoneId'),status:document.getElementById('waStatus').value,updated_at:new Date().toISOString()};const {error}=await servellesDb.from('hotel_whatsapp_connections').upsert(row,{onConflict:'hotel_id'});if(error)return alert(error.message);toastAdmin('WhatsApp settings saved');}async function savePms(){const row={hotel_id:ADMIN_CURRENT_HOTEL.id,provider:document.getElementById('pmsProvider').value,property_id:val('pmsPropertyId'),status:document.getElementById('pmsStatus').value,notes:val('pmsNotes'),updated_at:new Date().toISOString()};const {error}=await servellesDb.from('hotel_pms_connections').upsert(row,{onConflict:'hotel_id'});if(error)return alert(error.message);toastAdmin('PMS settings saved');}function val(id){return document.getElementById(id).value.trim()||null;}function toastAdmin(text){const n=document.createElement('div');n.className='admin-toast';n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),2200);}
ensureAdminSidebar();
document.getElementById('adminLogoutBtn')?.addEventListener('click',()=>servellesDb.auth.signOut());document.getElementById('returnAdminBtn')?.addEventListener('click',returnToAdmin);document.getElementById('adminBackBtn')?.addEventListener('click',backToHotelOverview);document.getElementById('saveHotelBtn')?.addEventListener('click',saveHotelDetails);document.getElementById('removeHotelBtn')?.addEventListener('click',removeCurrentHotel);document.getElementById('addDepartmentBtn')?.addEventListener('click',addDepartment);document.getElementById('addRoomBtn')?.addEventListener('click',addRoom);document.getElementById('saveWhatsAppBtn')?.addEventListener('click',saveWhatsApp);document.getElementById('savePmsBtn')?.addEventListener('click',savePms);