const requests = [
{id:1,room:'18',type:'housekeeping',category:'Towels',icon:'▤',message:'Hi, could we have another couple of bath towels please?',department:'Housekeeping',status:'new',received:'09:28',minutes:13,guest:'Mr. James Anderson',target:15,notes:[]},
{id:2,room:'22',type:'roomservice',category:'Beverages',icon:'♨',message:'Can we have a bottle of Sauvignon Blanc please?',department:'Room Service',status:'new',received:'09:30',minutes:11,guest:'Ms. Claire Baker',price:32,chargeable:true,target:10,notes:[]},
{id:3,room:'31',type:'engineering',category:'Hot water',icon:'⚒',message:"The shower isn't getting hot this morning.",department:'Engineering',status:'new',received:'09:33',minutes:8,guest:'Mr. David Cole',target:15,notes:[]},
{id:4,room:'7',type:'concierge',category:'Transport',icon:'◈',message:'Could you book us a taxi to the airport for 7am tomorrow?',department:'Concierge',status:'new',received:'09:34',minutes:7,guest:'Mrs. Helen Morris',target:15,notes:[]},
{id:5,room:'14',type:'housekeeping',category:'Pillows',icon:'▤',message:'Two firmer pillows please.',department:'Housekeeping',status:'active',received:'09:18',minutes:23,guest:'Mr. Patel',accepted:'09:21',target:15,notes:['Housekeeping runner notified.']},
{id:6,room:'22',type:'roomservice',category:'Room Service',icon:'♨',message:'2 club sandwiches, fries and two cokes please.',department:'Room Service',status:'active',received:'09:30',minutes:11,guest:'Ms. Claire Baker',accepted:'09:32',price:42.50,chargeable:true,order:true,pos:true,billed:true,kitchen:true,kitchenStatus:'preparing',target:30,items:['2 × Club sandwich','1 × Fries','2 × Coca-Cola'],notes:['Kitchen ticket #1842 sent.']},
{id:7,room:'4',type:'housekeeping',category:'Amenities',icon:'▤',message:'Extra shower gel please.',department:'Housekeeping',status:'completed',received:'08:50',minutes:11,accepted:'08:52',completed:'09:01',guest:'Mr. Lewis',target:15,notes:[]},
{id:8,room:'26',type:'engineering',category:'Lighting',icon:'⚒',message:'Bedside lamp not working.',department:'Engineering',status:'completed',received:'08:41',minutes:25,accepted:'08:45',completed:'09:06',guest:'Mrs. Day',target:20,notes:[]},
{id:9,room:'11',type:'concierge',category:'Luggage',icon:'◈',message:'Can someone collect our luggage please?',department:'Concierge',status:'completed',received:'08:30',minutes:10,accepted:'08:31',completed:'08:40',guest:'Mr. Fraser',target:15,notes:[]}
];
const departments=['Housekeeping','Room Service','Engineering','Spa','Concierge','Front Office','Duty Manager'];
const views=['home','new','active','orders','departments','completed','placeholder'];
let selectedDepartment=null;
const $=id=>document.getElementById(id);
function showView(name){views.forEach(v=>$(v+'View')?.classList.toggle('active-view',v===name));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===name||( ['active','completed'].includes(name)&&n.dataset.nav==='new')));if(['new','active','completed'].includes(name))renderLists();if(name==='orders')renderOrders();if(name==='departments')renderDepartments()}
document.querySelectorAll('[data-open-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.openView)));
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{let n=b.dataset.nav;if(['home','new','orders','departments'].includes(n))showView(n);else showPlaceholder(n)}));
function showPlaceholder(name){const titles={conversations:'Conversations',guests:'Guest Directory',reports:'Reports & Service Levels',team:'Team',settings:'Settings'};$('placeholderTitle').textContent=titles[name]||'Coming Soon';$('placeholderCopy').textContent='Reserved for the connected-data build. The operational request, department and room-service flows are live in this prototype.';showView('placeholder')}
function sla(r){if(r.status==='completed')return '';let m=r.minutes||0,t=r.target||15,c=m>=t?'overdue':m>=t*.75?'warning':'';return `<span class="service-clock ${c}">◷ ${m}m / ${t}m</span>`}
function requestCard(r){let active=r.status==='active',completed=r.status==='completed';return `<article class="request-card"><div class="request-meta"><div class="request-icon ${r.type}">${r.icon}</div><div class="request-copy"><h3>ROOM ${r.room} ${r.urgent?'<span class="urgent-pill">URGENT</span>':''}${sla(r)} ${active?'<span class="status-pill">IN PROGRESS</span>':''}</h3><blockquote>“${r.message}”</blockquote><div class="suggested">${active||completed?'Department':'Suggested'}: ${r.department} · ${r.category}${r.price?` · <span class="price">£${r.price.toFixed(2)}</span>`:''}</div></div></div><div class="request-actions">${r.status==='new'?`<button class="action-btn" onclick="confirmRequest(${r.id})">✓ CONFIRM</button><button class="action-btn dark" onclick="openTransfer(${r.id})">→ TRANSFER</button><button class="action-btn dark" onclick="openReply(${r.id})">◌ REPLY</button>`:''}${r.status==='active'?`<button class="action-btn" onclick="openRequest(${r.id})">OPEN</button><button class="action-btn dark" onclick="openReply(${r.id})">◌ REPLY</button><button class="action-btn dark" onclick="completeRequest(${r.id})">✓ COMPLETE</button>`:''}${completed?`<button class="action-btn dark" onclick="openRequest(${r.id})">VIEW HISTORY</button>`:''}</div></article>`}
function renderLists(){let sort=a=>a.sort((x,y)=>(y.urgent?1:0)-(x.urgent?1:0)||(y.minutes||0)-(x.minutes||0));$('newRequestsList').innerHTML=sort(requests.filter(r=>r.status==='new')).map(requestCard).join('')||'<div class="placeholder-card">No new requests.</div>';$('activeRequestsList').innerHTML=sort(requests.filter(r=>r.status==='active')).map(requestCard).join('')||'<div class="placeholder-card">No active requests.</div>';$('completedRequestsList').innerHTML=requests.filter(r=>r.status==='completed').map(requestCard).join('')||'<div class="placeholder-card">Nothing completed yet.</div>';$('newCount').textContent=requests.filter(r=>r.status==='new').length;$('activeCount').textContent=requests.filter(r=>r.status==='active').length;$('completedCount').textContent=requests.filter(r=>r.status==='completed').length;$('orderCount').textContent=requests.filter(r=>r.order&&r.status!=='completed').length}
function openRequest(id){let r=requests.find(x=>x.id===id);if(!r)return;$('drawerTitle').textContent=`Room ${r.room} · ${r.category}`;let billing=r.chargeable?`<div class="detail-panel billing-panel"><h4>Charge & billing</h4><p><b>Amount:</b> £${(r.price||0).toFixed(2)}<br><b>Room posting:</b> ${r.billed?'✓ Posted to room':'Awaiting charge'}${r.order?`<br><b>POS:</b> ${r.pos?'✓ Sent':'Awaiting'}<br><b>Kitchen:</b> ${r.kitchen?'✓ Ticket sent':'Awaiting'}`:''}</p>${!r.billed?`<div class="billing-actions"><button class="action-btn" onclick="postCharge(${r.id})">POST TO ROOM</button><button class="action-btn dark" onclick="takePayment(${r.id})">TAKE PAYMENT</button><button class="action-btn dark" onclick="waiveCharge(${r.id})">WAIVE</button></div>`:''}</div>`:'';let order=r.order?`<div class="detail-panel"><h4>Kitchen progress</h4><div class="order-track"><div class="step done">Received</div><div class="step done">Confirmed</div><div class="step ${r.pos?'done':''}">POS</div><div class="step ${r.kitchen?'done':''}">Kitchen</div><div class="step ${r.kitchenStatus==='ready'?'done current':'current'}">${r.kitchenStatus==='ready'?'Ready':'Preparing'}</div><div class="step ${r.kitchenStatus==='delivered'?'done':''}">Delivered</div></div></div>`:'';$('drawerContent').innerHTML=`<div class="detail-panel"><span class="small-label">ROOM ${r.room}</span><h2 style="font-size:34px;margin:4px 0 8px">${r.category}</h2><div class="guest-message">${r.message}</div>${r.urgent?'<div class="urgent-pill" style="display:inline-block;margin:12px 0 0">URGENT</div>':''}</div><div class="detail-grid" style="margin-top:18px"><div class="detail-panel"><h4>Request information</h4><p><b>Department:</b> ${r.department}<br><b>Guest:</b> ${r.guest}<br><b>Received:</b> ${r.received}${r.accepted?`<br><b>Accepted:</b> ${r.accepted}`:''}${r.completed?`<br><b>Completed:</b> ${r.completed}`:''}</p>${sla(r)}</div><div class="detail-panel"><h4>Actions</h4>${r.status==='new'?`<button class="action-btn" onclick="confirmRequest(${r.id})">✓ CONFIRM & ASSIGN</button>`:''}<button class="action-btn dark" onclick="openTransfer(${r.id})">→ TRANSFER</button><button class="action-btn dark" onclick="openReply(${r.id})">◌ REPLY TO GUEST</button>${r.status==='active'?`<button class="action-btn" onclick="completeRequest(${r.id})">✓ COMPLETE REQUEST</button>`:''}<button class="action-btn danger" onclick="toggleUrgent(${r.id})">⚑ ${r.urgent?'REMOVE URGENT':'MARK AS URGENT'}</button></div></div>${billing}${order}<div class="detail-panel" style="margin-top:18px"><h4>Internal staff notes</h4>${(r.notes||[]).map(n=>`<div class="internal-note">${n}</div>`).join('')||'<p>No internal notes yet.</p>'}<textarea id="noteText" rows="3" placeholder="Add an internal note..."></textarea><button class="secondary-btn" onclick="addNote(${r.id})">ADD NOTE</button></div>`;openDrawer()}
function openDrawer(){$('requestDrawer').classList.remove('hidden');$('drawerOverlay').classList.remove('hidden')}function closeDrawer(){$('requestDrawer').classList.add('hidden');$('drawerOverlay').classList.add('hidden')}$('closeDrawer').onclick=closeDrawer;$('drawerOverlay').onclick=closeDrawer;
function confirmRequest(id){let r=requests.find(x=>x.id===id);r.status='active';r.accepted='09:41';toast(`Room ${r.room} accepted by ${r.department}`);renderAll();openRequest(id)}
function completeRequest(id){let r=requests.find(x=>x.id===id);if(r.chargeable&&!r.billed&&!r.waived){toast('Resolve the guest charge before completing this request.');openRequest(id);return}r.status='completed';r.completed='09:42';renderAll();closeDrawer();showView('completed')}
function openTransfer(id){let r=requests.find(x=>x.id===id);$('modalTitle').textContent='Transfer to Department';$('modalBody').innerHTML=`<div class="dept-list">${departments.map(d=>`<button class="dept" onclick="transferRequest(${id},'${d}')"><span><b>${d}</b><br><small>${deptSub(d)}</small></span><span>→</span></button>`).join('')}</div>`;openModal()}
function deptSub(d){return {Housekeeping:'Towels, amenities, cleaning','Room Service':'Food & beverage orders',Engineering:'Maintenance & repairs',Spa:'Spa & wellness requests',Concierge:'Transport, bookings, information','Front Office':'General guest enquiries','Duty Manager':'Urgent / escalation'}[d]||''}
function transferRequest(id,dept){let r=requests.find(x=>x.id===id);r.department=dept;r.status='active';r.accepted=r.accepted||'09:41';r.notes.push(`Transferred to ${dept}.`);closeModal();renderAll();openRequest(id)}
function openReply(id){let r=requests.find(x=>x.id===id);$('modalTitle').textContent=`Reply to Room ${r.room}`;$('modalBody').innerHTML=`<div class="reply-box"><div class="guest-message">${r.message}</div><textarea id="replyText" rows="5" placeholder="Type your reply to the guest..."></textarea><button class="primary-btn" style="width:100%;margin-top:12px" onclick="sendReply(${id})">SEND VIA WHATSAPP</button></div>`;openModal()}
function sendReply(id){let t=$('replyText').value.trim(),r=requests.find(x=>x.id===id);if(!t)return;r.notes.push('Guest reply queued: '+t);closeModal();toast('Reply queued to WhatsApp')}
function toggleUrgent(id){let r=requests.find(x=>x.id===id);r.urgent=!r.urgent;if(r.urgent)r.department=r.department||'Duty Manager';renderAll();openRequest(id)}
function addNote(id){let t=$('noteText').value.trim(),r=requests.find(x=>x.id===id);if(!t)return;r.notes.push(t);openRequest(id)}
function postCharge(id){let r=requests.find(x=>x.id===id);r.billed=true;r.pos=true;if(r.order)r.kitchen=true;r.notes.push(`£${r.price.toFixed(2)} posted to room.`);renderAll();openRequest(id);toast('Charge posted to room')}
function takePayment(id){let r=requests.find(x=>x.id===id);r.billed=true;r.notes.push('Payment taken directly.');openRequest(id);toast('Payment recorded')}
function waiveCharge(id){let r=requests.find(x=>x.id===id);r.waived=true;r.notes.push('Charge waived by staff.');openRequest(id);toast('Charge waived')}
function renderOrders(){let orders=requests.filter(r=>r.order&&r.status!=='completed');$('ordersBoard').innerHTML=orders.map(r=>`<article class="order-card"><div class="order-card-head"><div><span class="small-label">ROOM ${r.room} · ${r.guest}</span><h3>Room Service Order #${1800+r.id}</h3></div><div class="order-total">£${r.price.toFixed(2)}</div></div><div class="order-items">${(r.items||[r.message]).join('<br>')}</div><div class="order-flags"><span class="flag ${r.pos?'done':'wait'}">${r.pos?'✓ POS':'POS pending'}</span><span class="flag ${r.billed?'done':'wait'}">${r.billed?'✓ Room billed':'Billing pending'}</span><span class="flag ${r.kitchen?'done':'wait'}">${r.kitchen?'✓ Kitchen ticket':'Kitchen pending'}</span><span class="flag ${r.kitchenStatus==='ready'||r.kitchenStatus==='delivered'?'done':'wait'}">${r.kitchenStatus||'awaiting kitchen'}</span></div><div class="order-actions"><button class="action-btn" onclick="orderStage(${r.id},'ready')">MARK READY</button><button class="action-btn dark" onclick="orderStage(${r.id},'delivered')">MARK DELIVERED</button><button class="action-btn dark" onclick="openRequest(${r.id})">OPEN ORDER</button></div></article>`).join('')||'<div class="placeholder-card">No live room-service orders.</div>'}
function orderStage(id,s){let r=requests.find(x=>x.id===id);r.kitchenStatus=s;r.notes.push(`Order marked ${s}.`);if(s==='delivered')toast(`Room ${r.room} order delivered`);renderOrders();if(!document.getElementById('requestDrawer').classList.contains('hidden'))openRequest(id)}
function renderDepartments(){let grid=$('departmentGrid');grid.innerHTML=departments.map(d=>{let active=requests.filter(r=>r.department===d&&r.status!=='completed').length;return `<button class="department-card ${selectedDepartment===d?'selected':''}" onclick="selectDepartment('${d}')"><strong>${d}</strong><span class="dept-count">${active}</span><span>live request${active===1?'':'s'}</span></button>`}).join('');$('departmentRequests').innerHTML=selectedDepartment?requests.filter(r=>r.department===selectedDepartment&&r.status!=='completed').map(requestCard).join(''):'<div class="placeholder-card">Select a department to view its live workload.</div>'}
function selectDepartment(d){selectedDepartment=d;renderDepartments()}
function openModal(){$('modal').classList.remove('hidden');$('modalOverlay').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden');$('modalOverlay').classList.add('hidden')}$('closeModal').onclick=closeModal;$('modalOverlay').onclick=closeModal;
function manualRequest(){$('modalTitle').textContent='New Manual Request';$('modalBody').innerHTML=`<div class="manual-form"><label class="label">Room<input id="manualRoom" placeholder="e.g. 12"></label><label class="label">Department<select id="manualDept">${departments.map(d=>`<option>${d}</option>`).join('')}</select></label><label class="label">Request<textarea id="manualMessage" rows="4" placeholder="What does the guest need?"></textarea></label><label class="label">Charge £ (optional)<input id="manualPrice" type="number" min="0" step="0.01" placeholder="0.00"></label><button class="primary-btn" onclick="createManualRequest()">CREATE REQUEST</button></div>`;openModal()}
function createManualRequest(){let room=$('manualRoom').value.trim(),message=$('manualMessage').value.trim(),dept=$('manualDept').value,price=parseFloat($('manualPrice').value||0);if(!room||!message)return;requests.unshift({id:Date.now(),room,type:dept==='Engineering'?'engineering':dept==='Room Service'?'roomservice':dept==='Concierge'?'concierge':'housekeeping',category:'Manual request',icon:'＋',message,department:dept,status:'new',received:'09:42',minutes:0,guest:'Guest',target:15,price:price||undefined,chargeable:price>0,notes:[]});closeModal();renderAll();showView('new');toast(`New request created for Room ${room}`)}
function toast(t){let e=document.createElement('div');e.className='notification-toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function renderAll(){renderLists();renderOrders();renderDepartments()}
$('manualRequestBtn').onclick=manualRequest;$('newOrderBtn').onclick=()=>{manualRequest();$('manualDept').value='Room Service'};
renderAll();
Object.assign(window,{openRequest,confirmRequest,completeRequest,openTransfer,transferRequest,openReply,sendReply,toggleUrgent,addNote,postCharge,takePayment,waiveCharge,orderStage,selectDepartment,createManualRequest});
